import { BusinessProfile } from '../types';

export function generateSchemaJsonLd(profile: BusinessProfile): string {
  const schema: Record<string, any> = {
    '@context': 'https://schema.org',
    '@type': mapCategoryToSchemaType(profile.identity.category),
    '@id': `https://answerready.ai/business/${profile.slug}#identity`,
    name: profile.identity.businessName,
    legalName: profile.identity.legalName || profile.identity.businessName,
    alternateName: profile.identity.brandName,
    description: profile.identity.description,
    url: profile.contact.website,
    telephone: profile.contact.phone,
    email: profile.contact.email,
    foundingDate: profile.identity.foundedYear,
    address: {
      '@type': 'PostalAddress',
      streetAddress: profile.contact.address.street,
      addressLocality: profile.contact.address.city,
      addressRegion: profile.contact.address.state,
      postalCode: profile.contact.address.zip,
      addressCountry: profile.contact.address.country || 'US',
    },
    areaServed: profile.identity.serviceAreas.map((area) => ({
      '@type': 'AdministrativeArea',
      name: area,
    })),
    openingHoursSpecification: profile.contact.hours.map((h) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: h.day,
      description: h.hours,
    })),
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: `${profile.identity.businessName} Services`,
      itemListElement: profile.services.map((srv, idx) => ({
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: srv.name,
          description: srv.description,
        },
        priceSpecification: {
          '@type': 'PriceSpecification',
          description: srv.pricing,
        },
        position: idx + 1,
      })),
    },
  };

  if (profile.trust.rating && profile.trust.reviewCount) {
    schema.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: profile.trust.rating,
      reviewCount: profile.trust.reviewCount,
      bestRating: '5',
      worstRating: '1',
    };
  }

  // Add FAQ Page schema if approved FAQs exist
  const approvedFaqs = profile.faqs.filter((f) => f.status === 'approved');
  if (approvedFaqs.length > 0) {
    schema.hasPart = {
      '@type': 'FAQPage',
      mainEntity: approvedFaqs.map((faq) => ({
        '@type': 'Question',
        name: faq.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: faq.answer,
        },
      })),
    };
  }

  return JSON.stringify(schema, null, 2);
}

function mapCategoryToSchemaType(category: string): string {
  const map: Record<string, string> = {
    Plumber: 'Plumber',
    HVAC: 'HVACBusiness',
    Roofer: 'RoofingContractor',
    Electrician: 'Electrician',
    Contractor: 'GeneralContractor',
    Dentist: 'Dentist',
    Doctor: 'MedicalClinic',
    Lawyer: 'LegalService',
    Realtor: 'RealEstateAgent',
    'Auto Shop': 'AutoRepair',
    Restaurant: 'Restaurant',
    'Bakery / Cafe': 'Bakery',
    'Hair Salon': 'BeautySalon',
    Barber: 'BarberShop',
    'Cleaning Service': 'HomeAndConstructionBusiness',
    Landscaper: 'GardenStore',
    Hotel: 'Hotel',
    'Retail Store': 'Store',
    'E-commerce': 'OnlineBusiness',
    Accountant: 'AccountingService',
    'Financial Advisor': 'FinancialService',
    Consultant: 'ProfessionalService',
    Freelancer: 'Person',
    Nonprofit: 'NGO',
  };
  return map[category] || 'LocalBusiness';
}

export function generateMarkdownKnowledgeFile(profile: BusinessProfile): string {
  const approvedFaqs = profile.faqs.filter((f) => f.status === 'approved');

  return `# ${profile.identity.businessName} - AI Knowledge Profile
*Verified Knowledge Source for AI Assistants, Search Engines & Agents*
*Generated by AnswerReady AI | Updated: ${profile.updatedAt}*

---

## 1. Business Identity
- **Official Name:** ${profile.identity.businessName}
- **Legal Entity:** ${profile.identity.legalName}
- **Brand / Alternate Name:** ${profile.identity.brandName || profile.identity.businessName}
- **Industry & Category:** ${profile.identity.industry} (${profile.identity.category})
- **Tagline:** "${profile.identity.tagline}"
- **Founded Year:** ${profile.identity.foundedYear}
- **Short AI Description:** ${profile.identity.shortAiDescription}
- **Full Description:** ${profile.identity.description}
- **Physical Locations:** ${profile.identity.locations.join(', ')}
- **Official Service Areas:** ${profile.identity.serviceAreas.join(', ')}

---

## 2. Contact & Hours
- **Primary Phone:** ${profile.contact.phone}
${profile.contact.emergencyPhone ? `- **24/7 Emergency Line:** ${profile.contact.emergencyPhone}` : ''}
- **Official Email:** ${profile.contact.email}
- **Official Website:** ${profile.contact.website}
- **Headquarters Address:** ${profile.contact.address.street}, ${profile.contact.address.city}, ${profile.contact.address.state} ${profile.contact.address.zip}, ${profile.contact.address.country}
- **Online Booking URL:** ${profile.contact.appointmentUrl || 'Contact via phone or website'}

### Operating Schedule:
${profile.contact.hours.map((h) => `- **${h.day}:** ${h.hours}${h.isOpen247 ? ' (24/7 Dispatch)' : ''}`).join('\n')}

---

## 3. Verified Products & Services
${profile.services
  .map(
    (s, idx) => `### ${idx + 1}. ${s.name}
- **Description:** ${s.description}
- **Pricing & Fee Structure:** ${s.pricing}
- **Target Customer:** ${s.targetCustomer}
- **Problems Solved:** ${s.problemsSolved.join('; ')}
- **Available in Areas:** ${s.serviceAreas.join(', ')}
`
  )
  .join('\n')}

---

## 4. Business Facts & Specializations
- **Specialties:** ${profile.facts.specialties.join('; ')}
- **What Makes Us Different:** ${profile.facts.differentiators.join('; ')}
- **Years in Business:** ${profile.facts.yearsInBusiness} Years
- **Certifications & Accreditations:** ${profile.facts.certifications.join('; ')}
- **State Licenses:** ${profile.facts.licenses.join('; ')}
- **Industry Awards:** ${profile.facts.awards.join('; ')}
- **Brands & Equipment Carried:** ${profile.facts.brandsCarried.join('; ')}
- **Accepted Payment Methods:** ${profile.facts.paymentMethods.join(', ')}

### Verified Policies:
${profile.facts.policies.map((p) => `- **${p.name}:** ${p.details}`).join('\n')}

---

## 5. Trust Signals & Reputation
- **Aggregate Rating:** ${profile.trust.rating} / 5.0 (${profile.trust.reviewCount} verified reviews)
- **Accreditation:** ${profile.trust.accreditations.join(', ')}
${profile.trust.stats.map((st) => `- **${st.label}:** ${st.value}`).join('\n')}

---

## 6. Approved AI Knowledge Base (FAQ)
${approvedFaqs
  .map(
    (faq, idx) => `### Q${idx + 1}: ${faq.question}
**Verified Answer:** ${faq.answer}
`
  )
  .join('\n')}

---
*This file is machine-readable and optimized for RAG ingestion, AI assistant knowledge indexing, and customer support agent grounding.*
`;
}
